title: Residência BRISA
description: > # this means to ignore newlines until "baseurl:"
  Projeto Residência em TIC da BRISA - UnB FGA
permalink: ':title/'
baseurl: "/gh-pages" # the subpath of your site, e.g. /blog
url: "residenciabrisa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: chipro # if your site has a twitter account, enter it here

# Author Settings
author: 
author-img: lappis.png
about-author: Residência BRISA
social-twitter: 
social-github: 
social-linkedin: 
social-email: caguiar@unb.br

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
